# Generated by Django 4.1.2 on 2022-10-18 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("academic_level", models.CharField(max_length=200)),
                ("paper_type", models.CharField(max_length=200)),
                ("discipline", models.CharField(max_length=200)),
                ("topic", models.TextField(blank=True, null=True)),
                ("paper_instructions", models.TextField(blank=True, null=True)),
                ("updated", models.DateTimeField(auto_now=True)),
                ("created", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
