# Generated by Django 4.1.2 on 2022-10-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_remove_order_name_order_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="order", name="pages", field=models.IntegerField(default=0),
        ),
    ]
